[[language]]
name = "c"
file-types = [ "c", "h" ]

[[language]]
name = "go"
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "zig"
indent = { tab-width = 2, unit = "\t" }

[[grammar]]
name = "zig"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-zig", rev = "b670c8df85a1568f498aa5c8cae42f51a90473c0" }

[[language]]
name = "python"
language-servers = ["pylsp"]

[[language]]
name = "nasm"
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "\t" }

[language-server.godot]
command = "nc"
args = ["127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"]
