[[language]]
name = "c"
file-types = [ "c", "h" ]

[[language]]
name = "go"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "zig"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "zig"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-zig", rev = "b670c8df85a1568f498aa5c8cae42f51a90473c0" }

[[language]]
name = "python"
language-servers = ["pylsp"]

[[language]]
name = "nasm"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }

